### ISSUE TITLE
Missing new parameter $ent in overwritten redirectIfAuthenticated

### ISSUE THREAD

**Issue by loicbenoit** [stdonato/glpi-modifications#17]
At line 78 of file "src/index.php", function Auth::redirectIfAuthenticated is called without the new undocumented mandatory $ent added as an overwrite of the original GLPI core class in "src/inc/auth.class.php".

Please, either make this new parameter optional or provide it in src/index.php.

This bug breaks the index page of GLPI, making it impossible to log-in.

**Comment by stdonato** [comment]
Hi,
Thank's. I will fix ASAP.

Em ter, 23 de abr de 2019 às 12:08, Loic Benoit <notifications@github.com>
escreveu:

**Comment by stdonato** [comment]
Hi,
Please test this version.
Uninstall any previous version before test.
The bug was in front/login.php file. Already fix.

https://sourceforge.net/projects/glpithemes/files/9.4.2/Plugin_Modifications_1.3.2_GLPI_9.4.2.zip/download


Em ter, 23 de abr de 2019 às 12:09, Stevenes Donato <
stevenesdonato@gmail.com> escreveu:

**Comment by loicbenoit** [comment]
I confirm that the fix works.

**Comment by loicbenoit** [comment]
Still an issue when accessing the login page for the first time, without query parameter "noAUTO". In that case, index.php calls Auth::redirectIfAuthenticated() without any args.

**Comment by leoinfra** [comment]
INDEX.PHP estava assim 

 Auth::redirectIfAuthenticated();


Mudamos dessa forma:

 Auth::redirectIfAuthenticated();
 Auth::redirectIfAuthenticated(isset($_GET["redirect"])?$_GET["redirect"]:"");

**Comment by stdonato** [comment]
leoinfra, obrigado pelo feddback,
Vou testar a alteração o mais rápido possível.

**Comment by boscorelly** [comment]
is it fixed with last version ?

**Comment by stdonato** [comment]
Yes.

**Comment by boscorelly** [comment]
Can you close the issue ? :)
