### ISSUE TITLE
Unable to login when ldap auth is enable

### ISSUE THREAD

**Issue by tuxmaldo** [stdonato/glpi-modifications#18]
If I want to login when the LDAP auth is enabled, I have the following message : "empty username or password".
If I disable the ldap server and login with a local user, it works !
GLPI 9.4.2 and plugin 1.3.2

**Comment by boscorelly** [comment]
Did you tried with last version ?

**Comment by tuxmaldo** [comment]
It works with GLPI 9.4.3 and plugin 1.40
Thank you for this plugin.
