### ISSUE TITLE
Listagem no link de atrasados

### ISSUE THREAD

**Issue by magaiverpr** [stdonato/glpi-modifications#2]
Antes ao clicar no link de atrasados aparecia todos os chamados atrasados, inclusive os já fechados, o que não batia com o número que mostrava no quadrado.

Essa alteração corrige esse problema.

[PS: não sei alterar o código no github, segue abaixo a alteração]

`$href_due = "".$CFG_GLPI["root_doc"]."/front/ticket.php?is_deleted=0&criteria[0][field]=5&criteria[0]
 -	[searchtype]=equals&criteria[0][value]=".$_SESSION['glpiID']."&criteria[1][link]=AND&criteria[1][field]=82		 +	[searchtype]=equals&criteria[0][value]=".$_SESSION['glpiID']."&criteria[1][link]=AND&criteria[1][field]=82&criteria[1][searchtype]=equals&criteria[1][value]=1&criteria[3][link]=AND&criteria[3][field]=12&criteria[3][searchtype]=equals&criteria[3][value]=notclosed&search=Pesquisar&itemtype=Ticket&start=0";`

arquivo inc/indicator.inc.php linha 38/39

**Comment by stdonato** [comment]
Olá. Obrigado pela correção. Vou testar e aplicar assim que possível.

**Comment by magaiverpr** [comment]
lembrando que é naquela barra superior, a barra do técnico.

**Comment by stdonato** [comment]
Aplicado.
