### ISSUE TITLE
Do not work

### ISSUE THREAD

**Issue by arkdetech** [stdonato/glpi-modifications#26]

**Comment by arkdetech** [comment]
Do not work the plugin, no upload the background image

**Comment by sdedurana** [comment]
Same problem.

GET https://glpiexample.com/pics/bg/back.jpg?v=2019.07.16.14.11.11%20width= 404
config.php:321 GET https://glpiexample.com/pics/logo_big.png?v=2019.07.16.14.11.11%20width= 404
config.php?act=mod:215 Uncaught ReferenceError: templateResult is not defined
    at HTMLDocument.<anonymous> (config.php?act=mod:215)
    at i (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)
    at Function.ready (jquery.js:3582)
    at HTMLDocument.K (jquery.js:3617)

![image](https://user-images.githubusercontent.com/7501096/61315179-9a96f300-a7d4-11e9-8b1b-1cb7d2c9324b.png)

![image](https://user-images.githubusercontent.com/7501096/61315250-bc907580-a7d4-11e9-91a0-9fb0ea1408ee.png)

**Comment by dondarb** [comment]
Es un problema de permisos del SEslinux, hay 2 opciones, desactivarlo o con esta linea:

chcon -R -t httpd_sys_content_rw_t /var/www/html/glpi/

An extra recommendation, when you are configuring something or adding plugins it is good to activate the debugger option

**Comment by stdonato** [comment]
Hi, thanks for your feedback.
