### ISSUE TITLE
Processo de instalação

### ISSUE THREAD

**Issue by felipeslo** [stdonato/glpi-modifications#27]
Foi modificado o processo de instalaçao?

Pois mesmo colocando na pasta plugins ou renomeando pra mod. Não funciona adequadamente.

**Comment by felipeslo** [comment]
Engano meu.

**Comment by ofprieto** [comment]
como está o processo ?

**Comment by felipeslo** [comment]
1 Passo: Você renomeia para mod
2 Passo: coloca na pasta plugins.
