### ISSUE TITLE
Conflito com Plugin Oauth da Teclib

### ISSUE THREAD

**Issue by gubarba** [stdonato/glpi-modifications#29]
O plugin modifications conflita com o plugin de Oauth oficial da Teclib, diponibilizado pela glpi-network
A forma com que o modifications altera o index.php da aplicação, sobreescrevendo o arquivo, impede que os plugins convivam sem alterações manuais.
Workaround: Restorar o index.php.bak para index.php mantém-se as funcionalidades do modifications, com excessão da tela de login.
Sugestão: Separar a mudança da tela de login em outro plugin, tornando os plugins independentes e inclusive facilitando a integração da splash-screen com outros plugins.
Essa separação de escopos também direcionaria issues apenas para essa parte do projeto, por exemplo a issue do link https://github.com/stdonato/glpi-modifications/issues/10

**Comment by stdonato** [comment]
Há a opção de desabilitar a mudança da tela de login, voltando a usar a pagina index.php padrão. Mas vou fazer testes com o plugin da Teclib. Obrigado e desculpe levar 1 século para responder.
