### ISSUE TITLE
GLPI 9.2.4 + Modifications 1.1.8

### ISSUE THREAD

**Issue by kholyphoenix1** [stdonato/glpi-modifications#30]
Boa tarde.
Pessoal estou utilizando GLPI 9.2.4 + Modifications 1.1.8.
Fiz a alteração da pasta do Modifications para mod conforme a orientação.
Quando vou no Painel do GLPI -> Configurar -> Plugins -> Modifications em Status 
Informa: 'Para atualizar' e por esse motivo não consigo ativar o plugin.

Alguém poderia me orientar?
Obrigado!

**Comment by stdonato** [comment]
Olá. Você já tinha o plugin instalado? Há alguma pasta com o mesmo plugin,
mesmo que com outro nome?

Em qui, 15 de ago de 2019 16:00, Júnior <notifications@github.com> escreveu:

**Comment by kholyphoenix1** [comment]
Não, mais eu tenho um plugin do mesmo desenvolvedor que é o: Painel.
