### ISSUE TITLE
Can't access /front/plugin.php after clean install of mod 1.4.0 on GLPI 9.4.3

### ISSUE THREAD

**Issue by smarcos-starxpert** [stdonato/glpi-modifications#31]
Hello

After clean install of GLPI 9.4.3, i tried to install GLPI MODIFICATION last version (1.4.0)
After applying everything as it is adviced, when i want to install the plugin trought the web GUI, i get a blank page
When i look at the logs, that's what i get :

glpiphplog.ERROR: Plugin::getInfo() in /opt/glpi/inc/plugin.class.php line 1238
plugin_version_mod.old method must be defined!

**Comment by stdonato** [comment]
Hi,
Do you have any other folder with previous version, in plugin folder?
If you have more than one folder of same plugin, you will have a error.

Em ter, 20 de ago de 2019 05:13, smarcos-starxpert <notifications@github.com>
escreveu:

**Comment by smarcos-starxpert** [comment]
Hi,

Alright so you can not have old versions (renamed) in /plugins/ folder ?
That fixed the problem, thanks for replying !
