### ISSUE TITLE
unwanted style change made by Indicators

### ISSUE THREAD

**Issue by SilentBob999** [stdonato/glpi-modifications#34]
Hi,

With GLPI Modifications v1.4.0 and GLPI 9.4.4.

If we turn ON the "Indicators". Some style in the knowledge base are affected.  See an example below.

With Indicators-ON :
![glpi-modifications_Indicators-ON](https://user-images.githubusercontent.com/4992105/66843791-428a9c80-ef3b-11e9-9d51-443327f51b58.png)

With Indicators-OFF :
![glpi-modifications_Indicators-OFF](https://user-images.githubusercontent.com/4992105/66843847-559d6c80-ef3b-11e9-8fec-63e009f1ae84.png)

In edit mode, the background show like it should.

Thank you

**Comment by stdonato** [comment]
Hi, bug already fixed. 
I will update repo in a few hours.

**Comment by stdonato** [comment]
New release with fix.

**Comment by SilentBob999** [comment]
Hi,
thank a lot for the fast response and fix. I still have the issue with the table background.

glpi-modifications_1.5.1_Indicators-OFF:
![glpi-modifications_1 5 1_Indicators-OFF](https://user-images.githubusercontent.com/4992105/66921326-ee42f380-eff2-11e9-900d-7f11a8c5b8a7.png)

glpi-modifications_1.5.1_Indicators-ON:
![glpi-modifications_1 5 1_Indicators-ON](https://user-images.githubusercontent.com/4992105/66921341-f56a0180-eff2-11e9-9374-7525b435b69a.png)

glpi-modifications_1.5.1_EDIT:
![glpi-modifications_1 5 1_EDIT](https://user-images.githubusercontent.com/4992105/66921361-031f8700-eff3-11e9-8d5c-94cffeaf7f68.png)


Source :
`<p>Knowledge Base test</p>
<table style="font-family: 'Source Code Pro',Monaco,Menlo,Consolas,'Droid Sans Mono','Inconsolata','Courier New',monospace; width: 100%; border-collapse: collapse; background-color: #000000;" border="1">
<tbody>
<tr>
<td style="width: 100%;"><span style="color: #6a9955;"># The backgroup of this should be black</span><br /><span style="color: #549ad6;">[void]</span><span style="color: #549ad6;">[System.Reflection.Assembly]</span><span style="color: #d4d4d4;">::</span><span style="color: #d4d4c9;">LoadWithPartialName</span><span style="color: #ffffff;">(</span><span style="color: #c39178;">"MySql.Data"</span><span style="color: #ffffff;">)</span><br /><span style="color: #d4d4d4;">Get-GlpiItems</span><span style="color: #ffffff;"> </span><span style="color: #d4d4d4;">-ItemType</span><span style="color: #ffffff;"> </span><span style="color: #c39178;">"computer"</span><span style="color: #ffffff;"> </span><span style="color: #d4d4d4;">-Creds</span><span style="color: #ffffff;"> </span><span style="color: #7bdcfe;">$CredGlpi</span></td>
</tr>
</tbody>
</table>`

Thank you,
