### ISSUE TITLE
[Sugestão] Contador de chamados novos para nivel 1

### ISSUE THREAD

**Issue by magaiverpr** [stdonato/glpi-modifications#4]
Gostaria de sugerir que no caso de perfil de atendimento nv1, tenha um contador de chamados novos também, para ficar visual saber quantos chamados estão na fila sem dono.

**Comment by mauriciolamego** [comment]
Acho válido quando se tem uma equipe de técnico que por exemplo faz a distribuição de chamado, desta forma podemos acompanhar a contagem de chamado a serem distribuídos. OK! 👍
