### ISSUE TITLE
GLPI 9.4.5 esta funcionando esse plugin?

### ISSUE THREAD

**Issue by leoinfra** [stdonato/glpi-modifications#40]

**Comment by stdonato** [comment]
Ainda não. Devo liberar a versão no início da semana que vem.

**Comment by stdonato** [comment]
Poderia testar esta versão para o GLPI 9.4.5? Ainda não está aqui no github, mas vou subir assim que fizer mais uns testes.
https://drive.google.com/open?id=16RETzKErHTaHsTBRxPgZNWMHPgMf_W9F

**Comment by leoinfra** [comment]
Bom dia!
Vou testar hoje! Obrigado

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by leoinfra** [comment]
boa tarde!


Querido não funcionou para mim. o plugin instala normal mas aplicando as imagens não funciona.
Vou Olhar o Log e passar a ti.

 Obrigado!

________________________________
De: Stevenes Donato <notifications@github.com>
Enviado: terça-feira, 7 de janeiro de 2020 16:38
Para: stdonato/glpi-modifications <glpi-modifications@noreply.github.com>
Cc: leoinfra <leonardo.vin@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [stdonato/glpi-modifications] GLPI 9.4.5 esta funcionando esse plugin? (#40)


Poderia testar esta versão para o GLPI 9.4.5? Ainda não está aqui no github, mas vou subir assim que fizer mais uns testes.
https://drive.google.com/open?id=16RETzKErHTaHsTBRxPgZNWMHPgMf_W9F<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D16RETzKErHTaHsTBRxPgZNWMHPgMf_W9F&data=02%7C01%7C%7C6e73a5cd23c54a6c5d7408d793b9fbb8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637140299305438173&sdata=ae9uAqxfM4clI4DcTn3cxo%2FOlgev8CpfZA2Icg3ujsY%3D&reserved=0>

**Comment by leoinfra** [comment]
Pegamos esse erro, onde a imagem vai para pasta mas nao aplica

ReferenceError: templateResult is not defined
________________________________
De: Stevenes Donato <notifications@github.com>
Enviado: terça-feira, 7 de janeiro de 2020 16:38
Para: stdonato/glpi-modifications <glpi-modifications@noreply.github.com>
Cc: leoinfra <leonardo.vin@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [stdonato/glpi-modifications] GLPI 9.4.5 esta funcionando esse plugin? (#40)


Poderia testar esta versão para o GLPI 9.4.5? Ainda não está aqui no github, mas vou subir assim que fizer mais uns testes.
https://drive.google.com/open?id=16RETzKErHTaHsTBRxPgZNWMHPgMf_W9F<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D16RETzKErHTaHsTBRxPgZNWMHPgMf_W9F&data=02%7C01%7C%7C6e73a5cd23c54a6c5d7408d793b9fbb8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637140299305438173&sdata=ae9uAqxfM4clI4DcTn3cxo%2FOlgev8CpfZA2Icg3ujsY%3D&reserved=0>

**Comment by stdonato** [comment]
Baixe a versão mais recente e antes de instalar verifique as permissões e o proprietário da pasta do plugin. Deve ser os mesmos da pasta GLPI.

**Comment by perera10** [comment]
Boa tarde, quando vc ira atualizar para versão 9.4.5 ?

**Comment by stdonato** [comment]
Já está dicponível: https://github.com/stdonato/glpi-modifications/releases

**Comment by leoinfra** [comment]
boa tarde meu querido!

 Vou testar agora
 att
________________________________
De: Stevenes Donato <notifications@github.com>
Enviado: sexta-feira, 24 de janeiro de 2020 15:31
Para: stdonato/glpi-modifications <glpi-modifications@noreply.github.com>
Cc: leoinfra <leonardo.vin@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [stdonato/glpi-modifications] GLPI 9.4.5 esta funcionando esse plugin? (#40)


Já está dicponível: https://github.com/stdonato/glpi-modifications/releases<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstdonato%2Fglpi-modifications%2Freleases&data=02%7C01%7C%7Cc7423aea114d4d1a9f1008d7a10c71e2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637154947123429730&sdata=6nfJOIKxWPEIti4uvE4fHLprqH%2FBV0ZQ7xp6uNHa7qQ%3D&reserved=0>

**Comment by mscordeiro** [comment]
Olá, testei seu plugin, coloquei na pasta porém não carrega na ferramenta, pode me ajudar?

**Comment by stdonato** [comment]
Olá,
Renomeie a pasta do plugin para mod

Att,

Stevenes Donato

Em qui., 9 de abr. de 2020 às 00:21, mscordeiro <notifications@github.com>
escreveu:

**Comment by leoinfra** [comment]
Boa tarde querido aqui esta aplicando so o logo e logo index, o Background nao aplica fica  tudo desfocado quando aplicado.
