### ISSUE TITLE
Don't list on plugin screen

### ISSUE THREAD

**Issue by RuaanPG** [stdonato/glpi-modifications#42]
I uploaded the plugin for glpi / plugin to a shared web server and the plugin does not appear in GLPI.
![Don't listened](https://user-images.githubusercontent.com/29637468/72012449-c1d9f480-323a-11ea-99a4-1429574ad1df.png)

**Comment by stdonato** [comment]
Olá. Após descompactar a pasta certifique-se que o nome dela seja "mod" e verifique as permissões também.

**Comment by RuaanPG** [comment]
ok, deu tudo certo. 
Obrigado !
