### ISSUE TITLE
Implementações

### ISSUE THREAD

**Issue by jhweb2** [stdonato/glpi-modifications#43]
Olá, otimo plugin, tudo funcionando perfeitamente, gostaria de sugerir algumas melhorias para torna-lo ainda melhor, como:

![1](https://user-images.githubusercontent.com/53986027/72265263-f9f68400-35fa-11ea-8745-fd53ffc0cce4.png)
Esta parte funcionar igual o painel inicial, por exemplo, se eu tiver 100 entidades ele não me mostrar o total de chamados e sim o total de chamados daquela entidade, igual na imagem abaixo

![2](https://user-images.githubusercontent.com/53986027/72265345-20b4ba80-35fb-11ea-8774-bd2f7a426ea2.png)
Conforme for trocando de entidade ele ir mostrando apenas os chamados daquela entidade...

Outra coisa mas não sei se é possivel:
 - Filtrar os chamados por usuário e ao grupo em que ele se encontra, por exemplo, usuário A está no grupo 1 e 2, porém existe o grupo 3 e 4 e nesta lista aparece todos os chamados do sistema, repito, seria algo incrível e uma mão na roda

**Comment by stdonato** [comment]
Os indicadores na parte superior mostram apenas os chamados de usuário logado, são informações individuais.
A barra sim exibe os chamados da entidade. Inclusive já fiz a alteração para exibir os chamados no status Processando separados, como na imagem que você postou.
Não sei se entendi a questão dos grupos do último item. Poderia detalhar?
