### ISSUE TITLE
Versão 1.1.8 apresenta bug no GLPI 9.4.4

### ISSUE THREAD

**Issue by heliogiovani** [stdonato/glpi-modifications#44]
Tudo funciona bem, mas algumas figuras ficam quebradas e alguns campos de texto não permitem edição. Exemplo, quando entro no campo descrição para editá-lo (em modelos de chamados). A versão atual pede o 9.4.5 do GLPI. Será que vale à pena migrar? Acho que está muito cedo pra isso.

**Comment by stdonato** [comment]
A versão 1.5.1 funciona com o GLPI 9.4.4

**Comment by heliogiovani** [comment]
Obrigado pela rápida resposta. Parabéns pelo seu incrível trabalho. Desejo-lhe muito sucesso.
