### ISSUE TITLE
not showing fontawesome on page statistics

### ISSUE THREAD

**Issue by benjaminEORIS** [stdonato/glpi-modifications#48]
Hi, 

I tested the plug-in in versions 1.5.1 and 1.5.2 with glpi v9.4.4 and v9.4.5. 
i found a problem : 

when activated, in the tab statistics of tickets the font awesome icons isn't showing 

![image](https://user-images.githubusercontent.com/50371086/73192918-18e03480-412a-11ea-9d95-a2d8d260832d.png)

if i desactive the plug-in then it's working

![image](https://user-images.githubusercontent.com/50371086/73193204-7d9b8f00-412a-11ea-95f4-f4d39d7c7f80.png)

how fix-it ?

**Comment by stdonato** [comment]
Fixed.
If you want try, get the files styles.css and styles.min.css in src/css folder and copy to your GLPI server in glpi/plugins/mod/src/css, then disable and enable plugin again.  Or copy the 2 css files to glpi/css folder.

**Comment by benjaminEORIS** [comment]
I have download the files : 

- styles.css 
- styles.min.css

I have replace this files in folder mod/src/css and disable and enable plugin again.

it's not working.

**Comment by stdonato** [comment]
Please clear browser cache or reload your webserver.
Working in GLPI 9.4.4 and 9.4.5:
![Firefox_Screenshot_2020-01-28T14-41-07 463Z](https://user-images.githubusercontent.com/7674445/73273790-e7637980-41ba-11ea-8058-7e7c95ee3285.png)

**Comment by benjaminEORIS** [comment]
It's working, but i had to replace the files : 

- glpi/css/styles.css

- glpi/css/styles.min.css 

by the files modified by you. 

It's working for glpi 9.4.5 and mod v1.5.1 and v1.5.2

Thanks for this fix

**Comment by stdonato** [comment]
Thanks for the feedback.
