### ISSUE TITLE
user logged in names is hiding

### ISSUE THREAD

**Issue by Indarien** [stdonato/glpi-modifications#49]
When enabling plugin my logged in username doesnt show in right corner.

Before enable
https://prnt.sc/qugyor

After enable
https://prnt.sc/qugzcr

**Comment by stdonato** [comment]
Yes, is a feature. More space to indicators. 
You always can click the gears icon to view use name.

**Comment by Indarien** [comment]
So, i understand, but would be better if it will not be hide always, for example, create a small icon and you mouse over - shows you name and other elements that was removed.
