### ISSUE TITLE
Problems with /plugins/mod/scripts/*

### ISSUE THREAD

**Issue by emaw705** [stdonato/glpi-modifications#51]
Hi.

I'm using GLPI 9.4.3 and the "GLPIP-Modifications" plugins.

Viewing the "/files/_log/php-errors.log" I found that an error is repeated all the time:

![image](https://user-images.githubusercontent.com/48997363/74742466-663d5680-523d-11ea-9238-999bae7b02db.png)

This occurs when the "Indicators" and "Status Bar" options are disabled.

![image](https://user-images.githubusercontent.com/48997363/74742552-908f1400-523d-11ea-9bfa-2d39e9a99837.png)

I discovered that when the options are enabled, in "/plugins/mod/script/" exists the scripts "ind.js" and "stats.js". Then, when the options are disabled, the scripts are renamed to "ind.js.bak" and "stats.js.bak". After, if I want to re-enabled these options, the files aren't renamed to "ind.js" and "stats.js".

Also, when the options are disabled each interactions with GLPI throw the errors in "/files/_log/php-errors.log".

Some ideas to add to modifications plugins:

* Show the current status of "Indicators" and "Status Bar" with something like this:

![image](https://user-images.githubusercontent.com/48997363/74743066-891c3a80-523e-11ea-8e55-a0b49481e701.png)

or maybe hiding the button of the current status. For example, if the option is enable, hide the Enable button and only show the Disable button.

* Solve the problem with the check of scripts "ind.js" and "stats.js" when the options are disabled.

Best regards.

Emanuel

**Comment by stdonato** [comment]
Hi, thanks for your feedback.
I undestand your sugestions, but is indicators are on, you will seem the indicator in menu bar. If stats are on, you will see the stats bar on home page. 
I will check the log errors ASAP.
Regards,

**Comment by emaw705** [comment]
Hi @stdonato .

Yes, you're right.

It was just a suggestion to improve the visibility when entering to the plugin configuration.

Thank you for the quick response

Regards,

Emanuel
