### ISSUE TITLE
Ocultar barra de Status para alguns perfis especificos

### ISSUE THREAD

**Issue by vasconcellos01** [stdonato/glpi-modifications#52]
Ola, sei que hoje não existe essa possibilidade nativamente, mas de alguma forma é possível ocultar a barra de Status para um ou alguns perfis específicos no GLPI? Tenho essa necessidade e se for possível adicionar alguma modificação no código ou qualquer outra solução momentânea para essa situação, já me ajuda muito, se for necessário realizar alguma alteração no código, imagino que seja nas linhas do arquivo "stats.inc.php", estou certo?

Meu ambiente é o seguinte:
 - GLPI 9.4.4
 - Modifications 1.5.1

![Stats_Bar](https://user-images.githubusercontent.com/61768533/75842065-22565f80-5dae-11ea-9739-78f212315305.png)

Agradeço desde já.

Att,
Leonardo Vasconcellos

**Comment by stdonato** [comment]
Olá. É possível sim ocultar por perfis de usuário (padrão, técnico, etc), desde que edite o código. A minha máquina de desenvolvimento deu problema, mas assim que estiver no ar de novo passo para você como fazer.

**Comment by vasconcellos01** [comment]
Maravilha, obrigado pelo retorno, fico no aguardo.

**Comment by vasconcellos01** [comment]
Boa noite stdonato, imagino que você esteja bem atarefado, mas existe algo que você consiga já me passar referente a essa solicitação?
