### ISSUE TITLE
PHP Warning on install.php line 67

### ISSUE THREAD

**Issue by rafaeldomi** [stdonato/glpi-modifications#53]
PHP Warning (2): copy(): The second argument to copy() function cannot be a directory in [..]/glpi95/plugins/mod/install.php at line 67

Which is:
copy(GLPI_MOD_DIR.'/src/pics/logo_big-def.png', GLPI_ROOT.'/pics/')

And should be:
copy(GLPI_MOD_DIR.'/src/pics/logo_big-def.png', GLPI_ROOT.'/pics/logo_big-def.png')

**Comment by stdonato** [comment]
Fixed.
Thank you.

**Comment by rafaeldomi** [comment]
Semicolon missing in line 67, giving this error:
Uncaught Exception ParseError: syntax error, unexpected 'recurse_copy' (T_STRING) in [..]/glpi95/plugins/mod/install.php at line 68

**Comment by stdonato** [comment]
Thank's, again.

Em dom., 8 de mar. de 2020 às 20:30, rafaeldomi <notifications@github.com>
escreveu:
