### ISSUE TITLE
not work for me in GLPI 9.4.5

### ISSUE THREAD

**Issue by ortiga88** [stdonato/glpi-modifications#55]
I install the plugin but it does not appear in the plugin and I tried other versions and nothing could be missing from the packaging version ??? in addition to the source code as in other plugins ??

**Comment by Asiusblack** [comment]
Hi There!

Previous disconnect from GLPI

After, you need renname the folder to "mod" and move to the path ../glpi/plugins/

and finally reload Apache 

regards.

**Comment by ortiga88** [comment]
genial me ha funcionado gracias
