### ISSUE TITLE
Picture upload limited to 1MB

### ISSUE THREAD

**Issue by charleneauger** [stdonato/glpi-modifications#56]
Hi,
I noticed that picture upload is limited to 1MB. After some investigation I saw that there is an hardcoded limitation in the code. I think that it should not be restricted, user should be able to defined their owns limit.

Best regards,
Charlene Auger

**Comment by stdonato** [comment]
Hi,
I'll fix it ASAP.
Thanks.

**Comment by stdonato** [comment]
New size limit: 10MB
