### ISSUE TITLE
How to change the color to the clock icon?

### ISSUE THREAD

**Issue by edgarfabiancalderon** [stdonato/glpi-modifications#58]
![Captura](https://user-images.githubusercontent.com/64982932/81331131-bcfd4400-9066-11ea-899f-6ea93c7e1b7c.PNG)

How to change the color to the clock icon?

**Comment by stdonato** [comment]
Hi,
It's a code error. In file mod/inc/indicator.inc.php, line 127 change "far fa-clock"  to "fa fa-clock" .
