### ISSUE TITLE
First installation in 9.2.1 broke layout

### ISSUE THREAD

**Issue by meuced** [stdonato/glpi-modifications#6]
Hi,

First thanks for your work !

But i have a problem, with GLPI 9.2.1, first installation of plugin "modifications" (never installed before) broke the layout of glpi, like there is no more CSS (or bad CSS).
It happens when the plugin is just installed, activated or desactivated.
When removed, layout is OK.
Tested with Chrome, Firefox and IE11.
Cache totally cleared.

See cap screen.

I'm not the only one having this bug : http://forum.glpi-project.org/viewtopic.php?pid=343214

Let me know if you need other information.

Thanks by advance.

![2018-01-30 12-04-25](https://user-images.githubusercontent.com/1366378/35563129-08760932-05b6-11e8-9599-55c7d21df504.png)

**Comment by meuced** [comment]
Hi again,

After some tests, i found that all commands "exec" in install.php are not executed because (i think) GLPI is installed on Windows.

I copied css, fonts and pics manually and it's ok.

Do you know if this is possible to fix this ?

Thanks.

**Comment by stdonato** [comment]
HI,
That's just what I was going to ask
This plugin just works in linux,
I'll add a system check and a warning about this in further versions.

Regards,

Stevenes Donato


2018-01-30 8:09 GMT-04:00 meuced <notifications@github.com>:
