### ISSUE TITLE
Deprecate GLPIKEY usage

### ISSUE THREAD

**Issue by spirkaa** [stdonato/glpi-modifications#61]
LDAP SSO auth not working with this plugin installed since glpi release 9.4.6, because file [src/inc/auth.class.php](https://github.com/stdonato/glpi-modifications/blob/master/src/inc/auth.class.php) need to be updated. See [Deprecate GLPIKEY usage](https://github.com/glpi-project/glpi/commit/efd14468c92c4da43333aa9735e65fd20cbc7c6c#diff-f04e8372fd676d3642e8e3a443969a56)

**Comment by stdonato** [comment]
Hi, i'll fix ASAP.
Thank's for your feedback.

**Comment by stdonato** [comment]
Can you test the fix?
Download master file, uncompress and rename the folder to mod, then install plugin.
https://github.com/stdonato/glpi-modifications/archive/master.zip

**Comment by spirkaa** [comment]
Yes, it's working now

**Comment by stdonato** [comment]
Thank's. I'll create a new release.
