### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by lmonasterio-undav** [stdonato/glpi-modifications#65]
Hi. Im new on this. Can you tell how i must install the plugin please? Thanks a lot!

**Comment by stdonato** [comment]
Hi, download, unzip, rename folder to "mod" and install like any plugin.

**Comment by lmonasterio-undav** [comment]
Muchas gracias Stevens! Gran trabajo! Lo voy a probar y te cuento.
Thanks a lot Stevens! Great Work! Im gonna test it and tell you.

**Comment by lmonasterio-undav** [comment]
I could install it! Thanks! The problem is i can not change the background and logo images trough the plugin page...

**Comment by lmonasterio-undav** [comment]
To be more specific: when i try to upload a picture, nothings happen

**Comment by stdonato** [comment]
What you glpi and plugin versions? Check permissions and owner of plugin folder.

**Comment by lmonasterio-undav** [comment]
I have GLPI 9.4.6 and mod version 1.5.5. 

"Plugin" folder: drwxrwxr-x 20 glpi glpi  4096 Jun 17 13:44 plugins
"mod" folder: drwxrwxr-x  6 glpi     glpi       4096 Jun 16 11:09 mod

**Comment by lmonasterio-undav** [comment]
I give full permissions (777) to both folders and change user and group to root but still nothing...

**Comment by stdonato** [comment]
If your problem is just with background image, copy your image to pics/bg, for now. Is a workaround while i fix the plugin.

**Comment by lmonasterio-undav** [comment]
I wanna changle the logo pic. I change the permissions again, restart, and now it says

http://172.16.1.70/plugins/mod/uplogo.php
Not Found
The requested URL was not found on this server.

**Comment by lmonasterio-undav** [comment]
Folder content:

root@GLPI:/var/www/html/glpi/plugins/mod# ls -la
total 88
drwxrwxr-x  6 root root  4096 Jun 17 14:28 .
drwxrwxr-x 20 root root  4096 Jun 17 14:17 ..
drwxrwxr-x  2 root root  4096 Jun 17 14:17 ajax
-rwxrwxr-x  1 root root  7886 Jun 17 14:28 config.php
-rwxrwxr-x  1 root root  3256 Jun 17 14:28 config_prof.php
-rwxrwxr-x  1 root root 18092 Jun 17 14:28 COPYING.txt
-rwxrwxr-x  1 root root  1415 Jun 17 14:28 hook.php
drwxrwxr-x  2 root root  4096 Jun 17 14:17 inc
-rwxrwxr-x  1 root root  2648 Jun 17 14:28 install.php
-rwxrwxr-x  1 root root   286 Jun 17 14:28 README.txt
drwxrwxr-x  2 root root  4096 Jun 17 14:17 scripts
-rwxrwxr-x  1 root root  2628 Jun 17 14:28 setup.php
drwxrwxr-x  7 root root  4096 Jun 17 14:28 src
-rwxrwxr-x  1 root root  2934 Jun 17 14:28 uninstall.php
-rwxrwxr-x  1 root root  1821 Jun 17 14:28 upfile.php
-rwxrwxr-x  1 root root  1670 Jun 17 14:28 uplogo_int.php
-rwxrwxr-x  1 root root  1662 Jun 17 14:28 uplogo.php

**Comment by stdonato** [comment]
Are your URL application field filled with glpi url? Look at Configuration -> General.

**Comment by lmonasterio-undav** [comment]
Yes. Thats ok. Now, after a restart, its solved the problem of page not found, but when i try to change the logo, nothing happens... remains the default logo...

**Comment by lmonasterio-undav** [comment]
Solucionado! Le aplique owner al usuario de apache y grupo glpi a la carpeta glpi y funciono!
