### ISSUE TITLE
Issue with Glpi 9.5 

### ISSUE THREAD

**Issue by roshanroche** [stdonato/glpi-modifications#72]
Hi,

i get the following error with the plugin on glpi 9.5

glpiphplog.CRITICAL:   *** PHP Error (1): Cannot redeclare recurse_copy() (previously declared in /var/www/html/glpi/plugins/mod/install.php:9) in /var/www/html/glpi/plugins/mod/install.php at line 9 

error while loading plugin page

![image](https://user-images.githubusercontent.com/22425503/95308943-92c0e400-089b-11eb-8308-0c043c2a6ab1.png)

**Comment by stdonato** [comment]
Hi,
What is your plugins version? 2.0.0?

**Comment by roshanroche** [comment]
yea 2.0.0. i have uninstalled the old plugin. im trying it on Glpi 9.5.2

**Comment by stdonato** [comment]
I don't test the plugin with 9.5.2, yet.
Maybe some bug fixes make the plugin crash. I'll try ASAP.

**Comment by roshanroche** [comment]
Thank u bro 👍
