### ISSUE TITLE
Sem efeito nenhum na versão 9.5.2

### ISSUE THREAD

**Issue by fbsdev** [stdonato/glpi-modifications#73]
Bom dia, 

Fiz a conversão da minha base da 9.4.3 para a 9.5.2, copiei todos os Plugins,, o mod funcionou de primeira,, mas vi aqui que tem a versão 2.0.0.

Fiz como comentado, removi o mod e instalei novamente,, depois de instalar o GLPI ficou padrão,, ignorando o plugin. 

MOD ativo e desativado não está fazendo efeito nenhum.

Abraço,

Fabio.

**Comment by stdonato** [comment]
Bom dia,
Ainda não ceonsegui testar e homologar para o 9.5.2. Houve mudanças relativas à segurança que podem ter afetado o pugin.
Assim que tiver novidades, atualizarei o github.

**Comment by ricardo98365** [comment]
Olá amigo, instalei na versão 9.5.2 mas o Marketplace não funciona com o plugin ativado segue o print
![terça-feira440](https://user-images.githubusercontent.com/53305976/96611967-9b6ddd00-12d3-11eb-9626-0c580ee9d2aa.png)

**Comment by stdonato** [comment]
Olá. Para o GLPI 9.5.2 use a versão 2.0.1
Depois de baixar e extrair, renomeie a pasta para "mod"
Na pasta plugins do GLPI só pode haver uma pasta de cada lpugin, mesmo que estejam com nomes diferentes, não pode haver mais de uma do mesmo plugin.
Por fim, verifique as permissões e proprietário da pasta do plugin. Deve ser iguais às do GLPI.

**Comment by stdonato** [comment]
Corrigido na versão 2.0.2
