### ISSUE TITLE
Marketplace GLPI 9.5.2

### ISSUE THREAD

**Issue by ricardo98365** [stdonato/glpi-modifications#75]
Olá amigo, fiz a instalação do plugin versão 2.0.1 e quando tento acessar o Marketplace aparece um erro, segue o print da tela
![terça-feira440](https://user-images.githubusercontent.com/53305976/96612490-2fd83f80-12d4-11eb-94ed-06c0e678655e.png)

**Comment by stdonato** [comment]
Confirmei o problema. Prividenciarei a solução o mais breve possível.
