### ISSUE TITLE
SQL Error "1064": You have an error in your SQL syntax; near 'glpi_items_devicememories``.`size`) / COUNT(``glpi_items_devicememories``.`id...' at line 16

### ISSUE THREAD

**Issue by jcervantes-sipecom** [stdonato/glpi-modifications#76]
Hello, the error shown in the title is affecting the correct functionality of GLPI, as you can see in the link, some people have had the same error.

[https://github.com/glpi-project/glpi/issues/8140](https://github.com/glpi-project/glpi/issues/8140)
[https://github.com/glpi-project/glpi/issues/7997](https://github.com/glpi-project/glpi/issues/7997)

Once the plugin is deactivated and removed, as well as overwriting the files from the original GLPI package, or specifically the inc/search.class.php file by removing the patch from the mod plugin, the error is fixed.

**GLPI 9.5.2
PHP 7.2.24-0ubuntu0.18.04.7
mod                  Name: GLPI Modifications             Version: 2.0.1**

**Comment by stdonato** [comment]
Hi, 
New plugin version change only index.php file.
