### ISSUE TITLE
Can't desactivate indocators

### ISSUE THREAD

**Issue by babouche91** [stdonato/glpi-modifications#78]
When i click on desactivate i have this error:
`PHP Warning (2): rename(/var/www/html/glpi/plugins/mod/scripts/ind.js,/var/www/html/glpi/plugins/mod/scripts/ind.js.bak): Permission denied in /var/www/html/glpi/plugins/mod/config.php at line 42`

What do i need to do ?

**Comment by stdonato** [comment]
Hi, check folder and files permissions.

**Comment by babouche91** [comment]
Thanks it was the permission !
