### ISSUE TITLE
login page layout problem

### ISSUE THREAD

**Issue by abeulink** [stdonato/glpi-modifications#8]
Hello developer,

In GLPI 9.2.2 and plugin GLPI-Modifications version 1.1.5
AND after upgrading to latest version 9.2.3 of GLPI, new plugin GLPI-Modification version 1.1.8 

The login page is showing same layout problem :( 
How can we fix it? I was hoping you already fixed it in your version 1.1.8.

And where is background of login area?

![login page layout problem](https://user-images.githubusercontent.com/26407519/40112332-f560e774-5905-11e8-9a52-84989ce0f075.jpg)

**Comment by abeulink** [comment]
Hey Stevenes Donato, I have found your other work GLPI Themes. What is difference between GLPI-Modification and GLPI Themes?

**Comment by stdonato** [comment]
GLPI Themes is a old project, only for GLPI 0.85.x

Em qua, 16 de mai de 2018 às 08:53, abeulink <notifications@github.com>
escreveu:

**Comment by abeulink** [comment]
Thanks for fast reply, but after checking page of https://sourceforge.net/projects/glpithemes/.
Are you sure it is old project? 

But I saw on the page: please look at the weeks on the right side.

![project activity](https://user-images.githubusercontent.com/26407519/40118325-e9400b50-5919-11e8-92c7-1c0b0e5ba09b.jpg)

**Comment by stdonato** [comment]
What's your GLPI version an O.S.?
Check permissions of plugin folder and restart your web server (apache,
nginx)

Em qua, 16 de mai de 2018 às 09:53, abeulink <notifications@github.com>
escreveu:

**Comment by abeulink** [comment]
My work pc is Windows 10 and GLPI is installed on NAS QNAP server TVS-1282T.
We already checked permissions of plugin folder and restarted web server.
Still same problem :(

**Comment by abeulink** [comment]
My work pc is Windows 10 and GLPI is installed on NAS QNAP server TVS-1282T.
We already checked permissions of plugin folder and restarted web server.
Still same problem :(
